baseURL = 'https://turbulynx.github.io/blogs'
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Turbulynx"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "AI"
  website = "https://turbulynx.github.io/blogs/"
  authorInfo = " Order in disorderness "
  authorPostImage = "/img/author-post-img.jpg"

[Author]
  name = "AI"
  website = "https://turbulynx.github.io/blogs/"
  email = "turbulynx@gmail.com"
  facebook = "turbulynx"
  instagram = "turbulynx"
  youtube = "user/turbulynx"
  twitter = "turbulynx"
  linkedin = "turbulynx"
  github = "turbulynx"
  threads = "turbulynx"
  gitlab = "turbulynx"
  reddit = "turbulynx"
  stackoverflow = "users/XXXXXXX/turbulynx"
  snapchat = "turbulynx"
  spotify = "turbulynx"
  paypal = "turbulynx"
  telegram = "turbulynx"
  mastodon = "url"
  slack = "turbulynx"
  #bandcamp = "turbulynx"
  #itchio = "turbulynx"
  #vk = "turbulynx"
  #500px = "turbulynx"
  #kaggle = "turbulynx"
  #weibo = "turbulynx"
  #xing = "turbulynx"
  #bitbucket = "turbulynx"
  #soundcloud = "turbulynx"
  # codepen = "turbulynx"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"